
version: '3.7'
services:
  master:
    image: mariadb:10.6.4
    env_file: env
    ports:
      - "4001:3306"
    volumes:
      - ./conf.d/master.cnf:/etc/mysql/conf.d/my.cnf
      - ./initdb.d/sql/master:/docker-entrypoint-initdb.d
      - ./data/master:/var/lib/mysql:rw
    # command: mysqld --log-bin=mariadb-bin --binlog-format=ROW --server-id=3000 --log-slave-updates
    networks:
      - backend
    restart: on-failure

  slave1:
    image: mariadb:10.6.4
    env_file: env
    depends_on:
      - master
    ports:
      - "4002:3306"
    volumes:
      - ./conf.d/slave1.cnf:/etc/mysql/conf.d/my.cnf
      - ./initdb.d/sql/slave:/docker-entrypoint-initdb.d
      - ./data/slave1:/var/lib/mysql:rw
    # command: mysqld --log-bin=mariadb-bin --binlog-format=ROW --server-id=3001 --log-slave-updates
    networks:
      - backend
    restart: on-failure

  slave2:
    image: mariadb:10.6.4
    env_file: env
    depends_on:
      - master
    ports:
      - "4003:3306"
    volumes:
      - ./conf.d/slave2.cnf:/etc/mysql/conf.d/my.cnf
      - ./initdb.d/sql/slave:/docker-entrypoint-initdb.d
      - ./data/slave2:/var/lib/mysql:rw
    # command: mysqld --log-bin=mariadb-bin --binlog-format=ROW --server-id=3002 --log-slave-updates
    networks:
      - backend
    restart: on-failure

networks:
  backend:

