
version: '3.7'

services:
  master:
    image: mariadb:10.10
    env_file: ${ROOT_PROJECT_PATH:-.}/env/mariadb/prod_env
    ports:
      - "127.0.0.1:4001:3306"
    volumes:
      - ${MARIADB_PATH:-.}/conf.d/master.cnf:/etc/mysql/conf.d/my.cnf
      - ${MARIADB_PATH:-.}/initdb.d/sql/master:/docker-entrypoint-initdb.d
      - ${MARIADB_PATH:-.}/data/master:/var/lib/mysql:rw
    # command: mysqld --log-bin=mariadb-bin --binlog-format=ROW --server-id=3000 --log-slave-updates
    networks:
      - maxscale_network
    restart: on-failure

  slave1:
    image: mariadb:10.10
    env_file: ${ROOT_PROJECT_PATH:-.}/env/mariadb/prod_env
    depends_on:
      - master
    ports:
      - "127.0.0.1:4002:3306"
    volumes:
      - ${MARIADB_PATH:-.}/conf.d/slave1.cnf:/etc/mysql/conf.d/my.cnf
      - ${MARIADB_PATH:-.}/initdb.d/sql/slave:/docker-entrypoint-initdb.d
      - ${MARIADB_PATH:-.}/data/slave1:/var/lib/mysql:rw
    # command: mysqld --log-bin=mariadb-bin --binlog-format=ROW --server-id=3001 --log-slave-updates
    networks:
      - maxscale_network
    restart: on-failure

  slave2:
    image: mariadb:10.10
    env_file: ${ROOT_PROJECT_PATH:-.}/env/mariadb/prod_env
    depends_on:
      - master
    ports:
      - "127.0.0.1:4003:3306"
    volumes:
      - ${MARIADB_PATH:-.}/conf.d/slave2.cnf:/etc/mysql/conf.d/my.cnf
      - ${MARIADB_PATH:-.}/initdb.d/sql/slave:/docker-entrypoint-initdb.d
      - ${MARIADB_PATH:-.}/data/slave2:/var/lib/mysql:rw
    # command: mysqld --log-bin=mariadb-bin --binlog-format=ROW --server-id=3002 --log-slave-updates
    networks:
      - maxscale_network
    restart: on-failure

networks:
  maxscale_network:

