
RESET MASTER;

SET GLOBAL max_connections=1000;
SET GLOBAL gtid_strict_mode=ON;

CHANGE MASTER TO MASTER_HOST='master', MASTER_PORT=3306, MASTER_USER='${MASTER_USER}', MASTER_PASSWORD='${MASTER_ROOT_PASSWORD}', MASTER_USE_GTID=slave_pos;

START SLAVE;

